PHACDataHub/iidi-tech

aggregator/cloudbuild.yaml, cloudbuild.yaml, patient-browser/cloudbuild.yaml, synthesizer/cloudbuild.yaml
TODO: 
Note: I've not set up a trigger for the root cloudbuild file, it's currently pointless. If we don't end up mostly using JS/TS in this project, then it and the other root level JS ecosystem configuration can be tossed.
=> Configure service cloudbuilds

aggregator/aggregator.py, docker-compose.dev.yaml
Currently, the aggregation logic includes a `ReferenceDate` field derived from the occurrence time of individual immunizations. Given that the synthetic data distributes random occurrence time in a broad range, and only generates 100 records, the resulting data tends to have a single count per `ReferenceDate`. The `MIN_COUNT_THRESHOLD` default of 1 would then filter the returned aggregated results down to an empty list.
In reality, there's a much higher chance that more than one immunization within an age/gender group is administered on any given day where immunizations occur, so we could tune the synthetic data generation to create more date groupings. Might still be worth doing, but I also believe that occurrence time should not be the source of `ReferenceDate`.
My expectation is that …
=> Change `ReferenceDate` source in aggregator service logic

k8s/bc/virtual-service.yaml, k8s/federal/federator/deployment.yaml, k8s/federal/federator/kustomization.yaml, k8s/federal/federator/service.yaml, k8s/federal/kustomization.yaml, k8s/federal/namespace.yaml, k8s/federal/virtual-service.yaml, k8s/istio-ingress/gw-certificate.yaml, k8s/istio-ingress/mesh-gateway.yaml, k8s/on/virtual-service.yaml
Added manifests for federator service. Closes #132 
Note: Made the provincial aggregator end points accessible from outside the cluster and to be used in the federator service, since they will be available for use from the individual PTs.
Aggregate end point: https://federator.federal.iidi.alpha.phac.gc.ca/aggregated-data
=> Manifests for federal aggregator service

aggregator/cloudbuild.yaml, demo-portal/cloudbuild.yaml, federator/cloudbuild.yaml, patient-browser/cloudbuild.yaml, rshiny-dashboard/cloudbuild.yaml, synthesizer/cloudbuild.yaml, transfer-inbound/cloudbuild.yaml, transfer-outbound/cloudbuild.yaml
=> Update cloudbuilds for consistency, bash best practices, and image tag correctness

README.md, aggregator/aggregator.py, docker-compose.dev.yaml
Turned out the "bug" I was seeing was caused by a stale cached image for the aggregator service, local to my machine. I've bumped the tag to bust that cache, and added explicit documentation of the local docker image caching problem.
Also reverted the aggregator `ReferenceDate` behaviour, without bringing back deep argument drilling, to ensure that a single reference date is returned per-request.
=> Revert aggregator ReferenceDate single source of truth, fix for aggregators in local dev env

demo-portal/app.py, demo-portal/static/css/style.css, demo-portal/static/svg/Patient Transfer Dashboard.svg, demo-transfer-dashboard/.dockerignore, demo-transfer-dashboard/.nginx/nginx.conf, demo-transfer-dashboard/Dockerfile, demo-transfer-dashboard/cloudbuild.yaml, demo-transfer-dashboard/package.json, demo-transfer-dashboard/rsbuild.config.mjs, docker-compose.dev.yaml, eslint.config.mjs, k8s/demo-portal/deployment.yaml, package.json
TODO:
- could have let this wait for the k8s manifests, but trivial so I did it now
Follow up:
- create k8s manifests and update the `DEMO_TRANSFER_DASHBOARD_URL` env var in the `demo-portal` deployment
- I could do this, but no rush and I need to go back to other tasks
- tracked in #162
=> Transfer Dashboard DevEnv and DevOps

transfer-outbound/src/create_app.ts
Previously just returned the ID of the created job (or ID of the existing job if the provided patient ID and targeted province are already queued), now returns the same information as other endpoints (job ID but also processing state and etc).
=> Tweak the response body for the POST /transfer-request endpoint

federator/src/create_app.ts, node-dev-docker-env/wait_for_service.cjs, transfer-outbound/src/fhir_utils.ts, transfer-outbound/src/transfer_request_queue/transferRequest.d.ts, transfer-outbound/src/transfer_request_queue/transfer_stage_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_worker.ts
TODO:
- ~might be worth stripping some of the bundle metadata before storing it in the queue/sending it to the inbound endpoint~
- no longer storing bundles on the queue, so that portions no longer a concern
- whether metadata/certain fields should be stripped before transferring to the inbound endpoint is a more involved question, ultimately going to depend on provincial policies/legislation/data sharing agreements to some extent. Out of scope
- achieved by no longer storing the bundle information on the queue
Follow up:
- accepting configuration env vars for bundle content/filtering rules will be left off for later. See #110
Closes #112
=> Basic implemntation of get_patient_bundle_for_transfer

k8s/bc/virtual-service.yaml, k8s/on/virtual-service.yaml
Missed this in review. There were extraneous `-svc` suffixes in there. Alternatively, I could keep the `-svc` in the virtual service manifests and update the names in the corresponding `transfer-outbound-service.yaml` files, if we want `-svc` to be the naming convention :+1:
=> Correct the transfer-outbound virtual-service routes

k8s/bc/bc-transfer/transfer-outbound.yaml, k8s/on/on-transfer/transfer-outbound.yaml, transfer-outbound/package-lock.json, transfer-outbound/package.json, transfer-outbound/src/create_app.ts, transfer-outbound/src/env.ts
Configuring CORS so browsers will accept requests crossing from to the transfer-outbound APIs from either the deployed transfer dashboard OR localhost dev builds. Should unblock your connections @samiatoui.
=> transfer-outbound server CORS

demo-transfer-dashboard/Dockerfile, k8s/demo-transfer-dashboard/deployment.yaml
Could revisit this pattern later, but this is the quick/necessary fix for now. The build system injects the env var values it has at image build time, generating the static content that is then served at container run time. The static content is set by the time it's serving in the cluster, and setting the env vars there doesn't impact anything.
My bad for not noticing this sooner, I set up the dockerfile for this, and it's a offbeat pattern compared to the rest of the containers we're dealing with.
=> Move demo-transfer-dashboard env vars from run-time mounting to build-time args

transfer-outbound/src/create_app.ts, transfer-outbound/src/fhir_utils.ts
Without these 501 ("unimplemented") errors in the transfer-outbound FHIR utils, the transfer process will be able to move through all phases successfully (pending #181). Will help with developing/giving any early demos of the transfer dashboard within the team, if needed while #177 is still open.
=> Remove transfer-outbound 501 errors

docker-compose.dev.yaml, transfer-outbound/src/transfer_inbound_utils.ts
Fixes some of the bugs with transfering bundles from the outbound service to the inbound service (one in both local and deployed envs, one in local docker-compose only).
@niranjan-ramesh Please review, and once merged can you look in to a follow up item with the inbound end's validation for me? It's rejecting what I believe should be a valid bundle.
=> Outbound to inbound request fix

transfer-outbound/src/create_app.ts, transfer-outbound/src/fhir_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_request_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_stage_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_worker.ts
- Simplified the worker loop, removed the pre-transfer patient record "marking" phase, which also removes the need for a rollback step in the failure handling queue
- see TODO comments in code, I anticipate adding an additional work stage back in for explicitly "rejected" transfers, to differentiate validation failure cases from generic failure handling cases. That can be a followup PR though.
- The new logic is that a patient can't be transfered if its links includes a "replaced-by" entry (assumption that the patient record is no longer "authoritative", and the transfer request should be re-made targeting the newer, "replacing", record)
- Once a patient has been transfered in to a new province, a "replaced-by" link is added to the patient in the outbound system
- per the new …
=> Patient transfer metadata handling

docker-compose.dev.yaml, synthesizer/script.py
Corrected the `"PHIL"` code to `"PHILISOP"` and removed possibility of the exemption being set with a `None` value. Both were being caught and rejected by the inbound transfer spec validation.
=> Synthesizer exemption code fixes

transfer-inbound/src/create_app.ts, transfer-inbound/src/error_utils.test.ts, transfer-inbound/src/error_utils.ts, transfer-inbound/src/fhir_utils.test.ts, transfer-inbound/src/fhir_utils.ts, transfer-outbound/src/create_app.ts, transfer-outbound/src/fhir_utils.ts, transfer-outbound/src/transfer_request_queue/transferRequest.d.ts, transfer-outbound/src/transfer_request_queue/transfer_request_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_stage_utils.ts, transfer-outbound/src/transfer_request_queue/transfer_worker.ts
When the transfer-inbound server rejects a transfer bundle for validation failure reasons, want the queue to move to an explicit "rejected" state rather than throwing the response as an error. Throwing an error leads to retry attempts, which are pointless when the data itself is invalid.
TODO:
=> Add an explicit "rejected" terminal stage to the transfer-outbound worker queue

k8s/bc/aggregation-server/deployment.yaml, k8s/bc/aggregation-server/kustomization.yaml, k8s/bc/bc-transfer/kustomization.yaml, k8s/bc/bc-transfer/transfer-outbound.yaml, k8s/bc/hapi-fhir-server/database.yaml, k8s/bc/hapi-fhir-server/kustomization.yaml, k8s/bc/patient-browser/kustomization.yaml, k8s/bc/redis-server/kustomization.yaml, k8s/on/aggregation-server/deployment.yaml, k8s/on/aggregation-server/kustomization.yaml, k8s/on/hapi-fhir-server/kustomization.yaml, k8s/on/on-transfer/kustomization.yaml, k8s/on/on-transfer/transfer-outbound.yaml, k8s/on/patient-browser/kustomization.yaml, k8s/on/redis-server/kustomization.yaml
This update refactors CPU and memory requirements across multiple services to ensure efficient resource utilization while allowing burstable performance. Additionally, it updates service endpoints for `transfer-inbound` configurations in **British Columbia (BC) and Ontario (ON)**.
---
- **Requests:** `250m CPU`, `512Mi - 4Gi Memory` (based on workload type).
- **Limits:** `1-4 CPU`, `2-8Gi Memory` (allows dynamic scaling).
- **Applies to:**  
- `aggregator`
- `transfer-inbound`
- `transfer-outbound`
- `hapi-fhir-server`
- `patient-browser`
- `redis`
- Updated **internal service endpoints** for cross-province connectivity.
- **New Service Mappings:**
- `transfer-inbound-svc.bc.svc.cluster.local:3000`
- `transfer-inbound-svc.on.svc.cluster.local:3000`
- **Requests:** `50m CPU`, `56Mi …
=> Chore: Burstable Pods + Bug Fix

.devcontainer/devcontainer.json, .devcontainer/setup.sh, README.md, docker-compose.dev.yaml
Closes #215
TODO:
- fixed itself somewhere in the process of other minor cleanup I performed and/giving the codespace more resources
- this apparent issue was most visible in the synthesizers failing to communicate with the FHIR server, might have just been the FHIR servers/their required DBs choking on low resources and never getting ready, rather than a container networking problem 
- can be done be making an SSH tunnel from your local machine as needed, via `gh codespace ssh -- -L <debug port in coespace>:localhost:<local port>`. 
Optional/follow up:
=> Codespaces

docs/mirgration-test-checklist/migration-test-checklist.md
=> Add checklist for manual post-migration testing procedures

federator/src/create_app.ts, k8s/argocd/image-updater/git-creds.yaml
Had two options, either replace the contents of the `argocd/git-creds` secret with the GitHub app values (same content as `argocd-notifications-secret`), or update all application manifests to replace
```
argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
```
with
```
argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-notifications-secret
```
Went with the `argocd/git-creds` approach since there's always the possibility that the creds used for GitHub status notifications and image updater write-backs could diverge at some point (e.g. if we want to bother creating a distinct GitHub app for each).
=> Use GitHub app credentials for image update auth

docker-compose.dev.yaml, transfer-inbound/src/create_app.ts
Sample Issue : 
"rejection_reason": "Job ID 4: inbound-transfer service for \"ON\" responded to patient ID \"6094\" transfer with a \"400\" status.{\"error\":\"FHIR spec validation failed\",\"details\":[{\"location\":\"Bundle.entry[0].resource/*Patient/6094*/.meta.source, Line[1] Col[204]\",\"diagnostics\":\"URL value '#86d75961-8a0f-42' does not resolve\",\"details\":\"No details provided\"},{\"location\":\"Bundle.entry[1].resource/*AllergyIntolerance/6095*/.meta.source, Line[1] Col[1269]\",\"diagnostics\":\"URL value '#86d75961-8a0f-42' does not resolve\",\"details\":\"No details provided\"},{\"location\":\"Bundle.entry[2].resource/*Immunization/6096*/.meta.source, Line[1] Col[2022]\",\"diagnostics\":\"URL value '#86d75961-8a0f-42' does not resolve\",\"details\":\"No details …
=> fix (transfer-inbound) : removed meta.source from bundle to fix FHIR validation failure
